### ISSUE TITLE
(otelzap) otelcore level is being erased on With

### ISSUE THREAD

**Issue by nadavsenior-noma** [agoda-com/opentelemetry-go#12]
# Bug report

## Describe the bug

When zap is calling the `With` function on the `otelzap` core, the `With` function returns a new core but forgets
to clone the level as well, causing the new core to block `debug` log messages.

## To Reproduce

1. Create a zap logger with `otelzap` core. Make sure to set the level of the core to `debug`:
```
otelzap.NewOtelCore(loggerProvider, otelzap.WithLevel(zap.DebugLevel))
```

2. Create a child logger by calling to `logger.With`:
```
newLogger := logger.With(zap.String("module", module))
newLogger.Debug("test")
```

The debug message will be filtered out by the `With` function (`otelzap/core.go:56`)

## Expected behavior

When calling `With`, the newly created core should contain the same log level.

**Comment by chameleon82** [comment]
Resolved with https://github.com/agoda-com/opentelemetry-go/pull/16
