### ISSUE TITLE
Bug: slog.Group attributes get added without parent group names

### ISSUE THREAD

**Issue by scwagner** [agoda-com/opentelemetry-go#19]
# Bug report

## Describe the bug

When using a `slog.Group` as an attribute, the children attributes in the group get added as `otelAttribute` attributes with just their name, stripping off any group names.

## To Reproduce

Changing `doSomething` in `otel_hander_test.go` the following code demonstrates the issue:

```go
func doSomething(ctx context.Context) {
	slog.InfoContext(ctx, "hello slog", slog.String("myKey", "myValue"),
		slog.Group("myGroup", slog.String("groupKey", "groupValue")))
}
```

Updating the corresponding `assert.Contains` to the following:

```go
	assert.Contains(t, actual, "service.name=otelslog-example, service.version=1.0.0, first=value1, group1.second=value2, group1.group2.myKey=myValue, group1.group2.myGroup.groupKey=groupValue}")
```

still shows the test failing:

```
        	Error Trace:	/REDACTED/opentelemetry-go/otelslog/otel_handler_test.go:64
        	Error:      	"2024-05-21T11:31:40-04:00 INFO hello slog [scopeInfo: github.com/agoda-com/otelslog:0.0.1] {host.name=REDACTED, service.name=otelslog-example, service.version=1.0.0, first=value1, group1.second=value2, group1.group2.myKey=myValue, groupKey=groupValue}\n" does not contain "service.name=otelslog-example, service.version=1.0.0, first=value1, group1.second=value2, group1.group2.myKey=myValue, group1.group2.myGroup.groupKey=groupValue}"
        	Test:       	TestNewOtelHandler
```

## Expected behavior

The test would pass.

## Screenshots

N/A

## Other

I am willing to submit a PR with a fix for this issue.

**Comment by Admin661** [comment]
> Error:      	

Hello @scwagner is the issue resolved yet? You'll have to use the key lomptimal weblink and try it again.
