### ISSUE TITLE
Show Example output of log on README.md

### ISSUE THREAD

**Issue by martinyonatann** [agoda-com/opentelemetry-go#9]
# Feature request

## Type

- [ ] - Enhancement - completely new feature
- [x] - Improvement - make what we have better

## Is your feature request related to a problem? 

> No

## Describe the solution you'd like

>  please show example output of logs on document, so we can imagine before use this library.

## Additional context

> ![image](https://github.com/agoda-com/opentelemetry-go/assets/107392127/da860c9c-d8ad-4718-92d1-efef3c244f41)

**Comment by chameleon82** [comment]
Hi @martinyonatann,
Could you create MR with your suggestion? 
Current bridges provide trace context available in otlp format (traceID, spanID, traceFlag) along with structured logging information. Is it something you expect to see in the example?

**Comment by martinyonatann** [comment]
Hi @chameleon82 sorry I just saw your reply, yes is it.
